MvcProjeKampi/Controllers/AdminCategoryController.cs
using BLL.Concrete;
using BLL.ValidationRules;
using DAL.EntityFramework;
using EL.Concrate;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public ActionResult Index()
        {
            var catValues = cm.GetCategories();
            return View(catValues);
        }

        [HttpGet]
        public ActionResult AddCategory() 
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            CategoryValitator catVal = new CategoryValitator();
            ValidationResult result = catVal.Validate(p);
            if (result.IsValid)
            {
                cm.CategoryAddBLL(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var catValues = cm.GetByCategoryId(id);
            cm.CategoryDeleteBLL(catValues);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var catValue = cm.GetByCategoryId(id);
            return View(catValue);
        }

        [HttpPost]
        public ActionResult EditCategory(Category p)
        {
            cm.CategoryUpdateBLL(p);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Controllers/CategoryController.cs
using BLL.Concrete;
using BLL.ValidationRules;
using FluentValidation.Results;
using DAL.EntityFramework;
using EL.Concrate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetCategoryList()
        {
            var categoryvalues = cm.GetCategories();
            return View(categoryvalues);
        }

        [HttpGet]
        public ActionResult AddCategory()
        {

            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            //cm.AddCategoryBLL(p);
            CategoryValitator catVal = new CategoryValitator();
            ValidationResult results = catVal.Validate(p);
            if (results.IsValid)
            {
                cm.CategoryAddBLL(p);
                return RedirectToAction("GetCategoryList");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

MvcProjeKampi/Controllers/ContentController.cs
using BLL.Concrete;
using DAL.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class ContentController : Controller
    {
        // GET: Content

        ContentManager cm = new ContentManager(new EfContentDal());
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ContentByHeading(int id)
        {
            var value = cm.GetContentsById(id);
            var heading = hm.GetHeadingById(id);

            ViewBag.deger = heading;
            return View(value);
        }
    }
}

MvcProjeKampi/Controllers/HeadingController.cs
using BLL.Concrete;
using DAL.EntityFramework;
using EL.Concrate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class HeadingController : Controller
    {
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());
        // GET: Heading
        public ActionResult Index()
        {
            var hdngValues = hm.GetHeadings();
            return View(hdngValues);
        }
        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> catList = (from x in cm.GetCategories()
                                            select new SelectListItem
                                            {
                                                Text = x.CategoryName,
                                                Value = x.CategoryId.ToString()
                                            }).ToList();

            List<SelectListItem> wrtList = (from x in wm.GetWriters()
                                            select new SelectListItem
                                            {
                                                Text = x.WriterName + " " + x.WriterSurname,
                                                Value = x.WriterId.ToString()
                                            }).ToList();
            ViewBag.vlc = catList;
            ViewBag.vlw = wrtList;
            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading h)
        {
            h.HeadingDate = DateTime.Now;
            hm.HeadingAddBLL(h);
            return RedirectToAction("Index");
        }

        public ActionResult ContentByHeading()
        {

            return View();
        }
    }
}

MvcProjeKampi/Controllers/WriterController.cs
using BLL.Concrete;
using BLL.ValidationRules;
using DAL.EntityFramework;
using EL.Concrate;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class WriterController : Controller
    {
        WriterManager wm = new WriterManager(new EfWriterDal());
        WriterValidator wrtVal = new WriterValidator();
        // GET: Writer
        public ActionResult Index()
        {
            var wrtValues = wm.GetWriters();
            return View(wrtValues);
        }

        [HttpGet]
        public ActionResult AddWriter()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddWriter(Writer w)
        {
            ValidationResult result = wrtVal.Validate(w);
            if (result.IsValid)
            {
                wm.WriterAddBLL(w);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult EditWriter(int id)
        {
            var wrtValue = wm.GetWriterById(id);
            return View(wrtValue);
        }

        [HttpPost]
        public ActionResult EditWriter(Writer w)
        {
            ValidationResult result = wrtVal.Validate(w);
            if (result.IsValid)
            {
                wm.WriterUpdateBLL(w);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

MvcProjeKampi/Views/AdminCategory/AddCategory.cshtml
@model EL.Concrate.Category

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Kategori Ekleme</h1>
<br />
<br />
@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="mb-3">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
    </div>
    <div class="mb-3">
        @Html.Label("Kategori Açıklaması")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
    </div>
    <button class="btn btn-success">Kaydet</button>
    <a href="/AdminCategory/Index" class="btn btn-secondary">Geri</a>
}

MvcProjeKampi/Views/AdminCategory/EditCategory.cshtml
@model EL.Concrate.Category
@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Kategori Güncelle</h2>
@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
{
    <div class="mb-3">
        @Html.Label("Kategori Id")
        @Html.TextBoxFor(x => x.CategoryId, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
    </div>
    <div class="mb-3">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
    </div>
    <div class="mb-3">
        @Html.Label("Kategori Açıklaması")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
    </div>
    <button class="btn btn-success">Güncelle</button>
    <a href="/AdminCategory/Index" class="btn btn-secondary">Geri</a>
}

MvcProjeKampi/Views/AdminCategory/Index.cshtml
@using EL.Concrate
@model List<Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Kategoriler</h2>
<hr />
<section class="content">
    @if (Model.Count > 0)
    {<div class="card">
            <div class="card-body p-0">
                <table class="table table-striped table-bordered projects">
                    <thead>
                        <tr class="text-center">
                            <th>#</th>
                            <th>Kategori</th>
                            <th>Açıklama</th>
                            <th>Durum</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    @foreach (var item in Model)
                    {
                        <tbody>
                            <tr>
                                <td>@item.CategoryId</td>
                                <td>@item.CategoryName</td>
                                <td>@item.CategoryDescription</td>
                                <td>@item.CategoryStatus</td>
                                <td class="col-2">
                                    <a href="/AdminCategory/DeleteCategory/@item.CategoryId" class="btn btn-danger" title="Sil">
                                        <i class="nav-icon fas fa-trash-alt"></i>
                                    </a>
                                    <a href="/AdminCategory/EditCategory/@item.CategoryId" class="btn btn-warning" title="Güncelle">
                                        <i class="nav-icon fas fa-sync-alt"></i>
                                    </a>
                                    <a href="#" class="btn btn-primary" title="Başlıklar">
                                        <i class="nav-icon fas fa-pen-fancy"></i>
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    }
                </table>
            </div>
        </div>
    }
    else
    {
        <div class="alert alert-info p-2">
            <div class="row d-flex align-items-stretch">
                <span class="fas fa-info-circle"></span> Bu sayfada bir kayıt yoktur. Yeni kayıt eklemek için aşağıdaki butonu kullanınız.
            </div>
        </div>
    }
</section>
<hr />
<div class="content pb-3">
    <a href="/AdminCategory/AddCategory" class="btn btn-info">Yeni Kategori</a>
</div>

MvcProjeKampi/Views/Category/AddCategory.cshtml
@model EL.Concrate.Category
@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<h1>Yeni Kategori Ekleme</h1>
<br />
<br />
@using (Html.BeginForm("AddCategory", "Category", FormMethod.Post))
{
    <div class="mb-3">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName)
        @Html.ValidationMessageFor(x=>x.CategoryName)
    </div>
    <div class="mb-3">
        @Html.Label("Kategori Açıklaması")
        @Html.TextBoxFor(x => x.CategoryDescription)
        @Html.ValidationMessageFor(x => x.CategoryDescription)
    </div>
    <button>Kaydet</button>
}

@*<form method="post" class="col-6">
        <div class="mb-3">
            <input type="text" name="CategoryName" placeholder="Kategori Adı" class="form-control" />
        </div>
        <div class="mb-3">
            <input type="text" name="CategoryDescription" placeholder="Kategori Açıklaması" class="form-control" />
        </div>
        <button class="btn btn-primary">Ekle</button>
    </form>*@

MvcProjeKampi/Views/Category/GetCategoryList.cshtml
@using EL.Concrate
@model List<Category>

@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Açıklama</th>
        <th>Durum</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CategoryId</td>
            <td>@item.CategoryName</td>
            <td>@item.CategoryDescription</td>
            <td>@item.CategoryStatus</td>
        </tr>
    }
</table>
<br />
<a href="~/Category/AddCategory" class="btn btn-outline-success">Yeni Kategori</a>

MvcProjeKampi/Views/Category/Index.cshtml
@{
    Layout = null;
}
<link href="~/Content/bootstrap-reboot.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<h3>Mvc Kamp Tablo Örneği</h3>
<br />
<br />
<table class="table table-bordered table-striped">
    <tr>
        <th>Kategori Id</th>
        <th>Kategori Adı</th>
        <th>Kategori Açıklama</th>
        <th>Kategori Durum</th>
    </tr>
    <tr>
        <td>1</td>
        <td>Eğitim</td>
        <td>Eğitim Açıklaması</td>
        <td>True</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Spor</td>
        <td>Spor Açıklaması</td>
        <td>True</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Sinema</td>
        <td>Sinema Açıklaması</td>
        <td>True</td>
    </tr>
</table>
<button class="btn btn-outline-dark">Yeni Kategori</button>
<button class="btn btn-outline-warning">Kategori Listesi</button>
<button class="btn btn-outline-danger">Kategori Sil</button>

MvcProjeKampi/Views/Content/ContentByHeading.cshtml
@using EL.Concrate
@model List<Content>

@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yazılar</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <!-- The time line -->
        <div class="timeline">
            <!-- timeline time label -->
            @foreach (var item in Model)
            {


                <div class="time-label">
                    <span class="bg-success">@item.ContentDate.ToShortDateString()</span>
                </div>
                <!-- /.timeline-label -->
                <!-- timeline item -->
                <div>
                    <i class="fas fa-comment bg-yellow"></i>
                    <div class="timeline-item">
                        <h3 class="timeline-header"><a href="#">@(item.Writer.WriterName+" "+item.Writer.WriterSurname)</a></h3>
                        <div class="timeline-body">
                            @item.ContentText
                        </div>
                    </div>
                </div>
                <!-- END timeline item -->
            }
        </div>
    </div>
    <!-- /.col -->
</div>

MvcProjeKampi/Views/Heading/AddHeading.cshtml
@model EL.Concrate.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlık Ekle</h2>
<br />
@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="mb-3">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
    </div>
    <div class="mb-3">
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar")
        @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterId)
    </div>
    <button class="btn btn-success">Kaydet</button>
    <a href="/Heading/Index" class="btn btn-secondary">Geri</a>
}

MvcProjeKampi/Views/Heading/ContentByHeading.cshtml
@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yazılar</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <!-- The time line -->
        <div class="timeline">
            <!-- timeline time label -->
            <div class="time-label">
                <span class="bg-success">Tarih</span>
            </div>
            <!-- /.timeline-label -->
            <!-- timeline item -->
            <div>
                <i class="fas fa-comment bg-yellow"></i>
                <div class="timeline-item">
                    <h3 class="timeline-header"><a href="#">Test</a> Deneme</h3>
                    <div class="timeline-body">
                        İçerik
                    </div>
                </div>
            </div>
            <!-- END timeline item -->
        </div>
    </div>
    <!-- /.col -->
</div>

MvcProjeKampi/Views/Heading/Index.cshtml
@using EL.Concrate
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlıklar</h2>
<hr />
<section class="content">
    @if (Model.Count > 0)
    {
        <div class="card">
            <div class="card-body p-0">
                <table class="table table-bordered table-striped projects">
                    <thead>
                        <tr class="text-center">
                            <th>#</th>
                            <th>Başlık</th>
                            <th>Oluşturan</th>
                            <th>Kategori</th>
                            <th style="width:20%">İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.HeadingId</td>
                                <td>
                                    <a>@item.HeadingName</a>
                                    <br />
                                    <small>@item.HeadingDate.ToShortDateString()</small>
                                </td>
                                <td class="project-state">
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="~/Tema/dist/img/avatar.png">
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <span class="badge badge-success">@item.Category.CategoryName</span>
                                </td>
                                <td>
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingId">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="#">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="#">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }
    else
    {
        <div class="alert alert-info p-2">
            <div class="row d-flex align-items-stretch">
                <span class="fas fa-info-circle"></span> Bu sayfada bir kayıt yoktur. Yeni kayıt eklemek için aşağıdaki butonu kullanınız.
            </div>
        </div>
    }
</section>
<hr />
<div class="content pb-3">
    <a href="~/Heading/AddHeading" class="btn btn-info">Yeni Başlık</a>
</div>

MvcProjeKampi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcProjeKampi/Views/Writer/AddWriter.cshtml
@model EL.Concrate.Writer
@{
    ViewBag.Title = "AddWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yazar Ekle</h2>
<br />
@using (Html.BeginForm("AddWriter", "Writer", FormMethod.Post))
{
    <div class="mb-3">
        @Html.Label("Yazar Adı")
        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterName)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Soyadı")
        @Html.TextBoxFor(x => x.WriterSurname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterSurname)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Mail")
        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Şifre")
        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterPassword)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Görsel Linki")
        @Html.TextBoxFor(x => x.WriterImg, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterImg)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Unvanı")
        @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterTitle)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Hakkında")
        @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout)
    </div>
    <button class="btn btn-success">Kaydet</button>
    <a href="/Writer/Index" class="btn btn-secondary">Geri</a>
}

MvcProjeKampi/Views/Writer/EditWriter.cshtml
@model EL.Concrate.Writer
@{
    ViewBag.Title = "EditWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yazar Düzenle</h2>
<br />
@using (Html.BeginForm("EditWriter", "Writer", FormMethod.Post))
{
    <div class="mb-3">
        @Html.Label("Yazar Id")
        @Html.TextBoxFor(x => x.WriterId, new { @class = "form-control", @style = "editable:false" })
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Adı")
        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterName)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Soyadı")
        @Html.TextBoxFor(x => x.WriterSurname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterSurname)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Mail")
        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Şifre")
        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterPassword)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Görsel Linki")
        @Html.TextBoxFor(x => x.WriterImg, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterImg)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Unvanı")
        @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterTitle)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Hakkında")
        @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout)
    </div>
    <button class="btn btn-success">Güncelle</button>
    <a href="/Writer/Index" class="btn btn-secondary">Geri</a>
}

MvcProjeKampi/Views/Writer/WriterAdd.cshtml
@model EL.Concrate.Writer
@{
    ViewBag.Title = "WriterAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yazar Ekle</h2>
<br />
@using (Html.BeginForm("WriterAdd", "Writer", FormMethod.Post))
{
    <div class="mb-3">
        @Html.Label("Yazar Adı")
        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterName)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Soyadı")
        @Html.TextBoxFor(x => x.WriterSurname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterSurname)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Mail")
        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Şifre")
        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterPassword)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Görsel Linki")
        @Html.TextBoxFor(x => x.WriterImg, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterImg)
    </div>
    <div class="mb-3">
        @Html.Label("Yazar Hakkında")
        @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout)
    </div>
    <button class="btn btn-success">Kaydet</button>
}